/*
 * 라이선스 내용 블라블라~
 *//*
 * 라이선스 내용 블라블라~
 *//*
 * 라이선스 내용 블라블라~
 *//*
 * 라이선스 내용 블라블라~
 *//*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
