/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/8.14/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.1.20")
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.1.20")

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) } 
                }
            }
        }
    }
}

gradlePlugin {// 커스텀 플러그인 정의

    //`plugins.creating` 메서드를 사용하여 `greeting` 플러그인을 정의
    val greeting by plugins.creating {

        //플러그인 ID 정의
        id = "org.example.greeting"
        //플러그인 구현 클래스
        implementationClass = "org.example.LicensePlugin"
    }

    //`plugins.creating` 메서드를 사용하여 `myTask` 플러그인을 정의
    val myTask by plugins.creating {

        //플러그인 ID 정의
        id = "org.example.myTask"
        //플러그인 구현 클래스
        implementationClass = "org.example.MyPlugin"
    }

    val licenseFileTask by plugins.creating {

        //플러그인 ID 정의
        id = "org.example.licenseFile"
        //플러그인 구현 클래스
        implementationClass = "org.example.LicenseFilePlugin"
    }
}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
}
